### ISSUE TITLE
[Refactoring] SQL optimization

### ISSUE THREAD

**Issue by lenaorobei** [magento/adobe-stock-integration#1610]
Related to https://github.com/magento/adobe-stock-integration/issues/1578

As per code review optimized queries should be used.

Files to refactor:
- `MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Directory.php:22`
> It would be great to investigate possibility to use LIKE condition or Fulltext search instead of regexp usage since any query with regexp condition will scan the full table for matching records and don't use indexes. It may cause performance issues on the large image catalogs.

- `MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Duplicated.php:46`
- `MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/EntityType.php:43`
- `MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Keyword.php:44`
> It's always not a good idea to use subquery due to performance degradation. I prefer to separate requests and use simple select to retrieve hashes and pass them to the IN condition after.

**Comment by Nazar65** [comment]
```

    MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Directory.php:22

    It would be great to investigate possibility to use LIKE condition or Fulltext search instead of regexp usage since any query with regexp condition will scan the full table for matching records and don't use indexes. It may cause performance issues on the large image catalogs.

```
Yes, but in our case if we will use LIKE condition we will have bug with sub folders for example we have directories with path 'one/one' 'one/' and images from 'one/one' also will be show as in 'one/' directory, and REGEXP is what we needed because it get exactly what we needed and as a path string in media_gallery_asset table contains not only path, and  image name as well, so we will have unexpected behavior in some cases.
