### ISSUE TITLE
See more from series/model tabs to hide if result is empty

### ISSUE THREAD

**Issue by konarshankar07** [magento/adobe-stock-integration#677]
### Preconditions (*)

1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)

1. Login to admin panel
2. Open Magento Media Gallery (i.e. go to Cms -> Pages, edit the page and insert image)
3. Click "Search Adobe Stock" button to open images grid
4. Enter text `81214721` in search by keywords
5. Click on the image to open the image preview

### Expected result (*)

![image](https://user-images.githubusercontent.com/39480008/68542496-3a573d00-03d3-11ea-9277-eed330a7a320.png)

### Actual result (*)

![image](https://user-images.githubusercontent.com/39480008/68542490-23184f80-03d3-11ea-97d6-2888ab378b09.png)

**Comment by rogyar** [comment]
Hi folks. Currently, if there no items in "More from this series", we show the same image that is opened in the preview

![image](https://user-images.githubusercontent.com/2148959/69634884-7cc77d80-1053-11ea-887f-350ef982d13f.png)

Moreover, the very first image from "More from this series" is always the same image that is opened in the preview.

![image](https://user-images.githubusercontent.com/2148959/69635076-e21b6e80-1053-11ea-8262-30f3ccf36c0d.png)

So, technically it may not be empty. Should we change this behavior and hide the tab instead if there's only 1 image in the "More from this series" section? 

Thank you.

cc @sivaschenko.

**Comment by sivaschenko** [comment]
@rogyar you are right, however, it could be empty after merge of https://github.com/magento/adobe-stock-integration/pull/752

**Comment by rogyar** [comment]
Hi @sivaschenko. Thank you for the reference, that makes sense. I will proceed to work on that.

**Comment by rogyar** [comment]
Hi folks. I've investigated the current preview behavior and must admit that this change is not as straightforward as it seems to be. 

The problem is, once the preview is expanded we don't have information about a number of related images until a separate AJAX request for the related images is completed. So in the current implementation, we create empty tabs, wait for the related images request result, fill the tabs with the corresponding images. 
So, in the very beginning, we cannot hide a particular tab since we have no information about its contents. As a solution, we may hide all tabs until we get a response with the related images. However, the related images request takes some time and the visitor might not know that the functionality of the related images exists if the visitor goes through previews faster than he gets the related images. 

I hope the description is clear. So, we need a decision from the product owner perspective here

Thank you.

**Comment by sivaschenko** [comment]
Thanks for the investigation @rogyar ! I think we should display the tabs initially (supporting the most common case) and hide tabs when the data arrives.

@belbiy @tkacheva what do you think about this?

**Comment by konarshankar07** [comment]
Hello @rogyar ,
Thanks for the update. My suggestion is we can check if tab content is empty in javascript using observable `relatedImages` in `related.js` and hide the tab on the basis of the `relatedImages` observable. Let me know your thoughts

**Comment by rogyar** [comment]
Hi @konarshankar07. Right, thank you for the suggestion. 

I've been thinking in the same way. The only question, I've described above, what to do with the tabs until we have information about the related images. 
I will implement the solution suggested by @sivaschenko in the meantime.

Thank you!

**Comment by rogyar** [comment]
Hi @sivaschenko. I still haven't found an "elegant" solution for this case because of some underlying issues with data binding. If we use the related images observable, the solution will look something like [this one](https://github.com/magento/adobe-stock-integration/pull/818/files) with some additional work. 
A less complex approach is to hide tabs using selectors in the `related.js`, but this approach might affect the knockoutJS data flow consistency.
