### ISSUE TITLE
Configuration cannot be saved if Adobe Stock Integration is not configured

### ISSUE THREAD

**Issue by engcom-Delta** [magento/adobe-stock-integration#696]
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Adobe Stock Integration is not configured

### Steps to reproduce (*)

- Login to admin panel
- Navigate to  Stores -> Configuration -> System
- Change value for Full Page Cache->TTL for public content
- Click Save Config

### Expected result:
Configuration is saved
Success message is shown

### Actual result
Configuration cannot be  saved
No validation message is shown
![Peek 2019-11-12 16-30](https://user-images.githubusercontent.com/51681379/68680358-36115800-056a-11ea-9691-656efd1fde8f.gif)

**Comment by drpayyne** [comment]
Hi @engcom-Delta I tried to recreate what you described and I'm able to but with a few differences. All of the below points are common to any Admin configuration page and not specific to Adobe Stock Integration. I feel this is more of a bug in Magento itself and not Adobe Stock Integration
-  Page **doesn't save** without filling required fields in an entire page
-  When a required field is empty but the group is minimized, the validation error is still rendered but the group doesn't auto expand is view doesn't scroll to that indicating an error is present to the user

Regarding the Adobe Stock Integration fields, I don't think saving the configuration with Adobe Stock is enabled with empty fields is intended? If the setting is enabled, then the two required fields must be filled as far as I've understood since they are required field dependent on the enabled field.

**Comment by filmaj** [comment]
This is related to Story 6 (#29), configuring the integration.

The question this raises is what is the default state of the "Enable Adobe Stock" toggle in the configuration UI. I imagine the correct setup consists of:

- default state of "Enable Adobe Stock" is _disabled_. In this case, the API and Private Key fields should not be required, and other configuration options can be changed and saved without issue.
- if "Enable Adobe Stock" is enabled, the API and Private Key fields should be required (as is the case today).

@tkacheva does the above make sense to you? I think we need clarification from you on the default state of "Enable Adobe Stock".

**Comment by tkacheva** [comment]
@filmaj if Stock is disabled, the button in Media Gallery won't be there, right?

**Comment by tkacheva** [comment]
@belbiy My suggestion is to handle no API key as wrong API key scenario so the Search stock button is displayed in the Media Gallery. The button should be gone if Adobe Stock integration is disabled. So what is your opinion on required * on API field. Should it be there?

**Comment by filmaj** [comment]
If I understand @tkacheva's intention, the idea is we want to keep the "Search Adobe Stock" button available on the Media Gallery, which is tied to the "Enable Adobe Stock" toggle in the Admin configuration; if the toggle is disabled, the Search button is gone.

One 'workaround'  to the issue discussed was to remove the key fields from being `required`. This way, we can both leave the integration Enabled _and_ have empty API and Private Key fields. If the user tries to use the Adobe Stock Search with empty key fields, they will experience the same flow as when the user enters invalid keys. Hopefully I have described this correctly.

**Comment by belbiy** [comment]
Yeah, good point on not requiring the API key. We probably good with remove the `required` and have some sort of a message under the field saying what user should do to fully "Enable" Adobe Stock. I think it's ok, people are generally good with understanding the API keys being required to run an integration. Maybe we can be more prescriptive in the field message:

![Configuration](https://user-images.githubusercontent.com/752610/68883815-632f4900-06d7-11ea-985d-f477a7a350a2.png)

> Configure an Adobe Stock account on the Adobe.io to get the API Key (Client ID) and Client Secret. You will not be able to use the integration without both Key and Secret.

Can we also change the field labels to more closely represent what Adobe.io has? We can add the field disclamer to the last one. And then add the Test Connection button.
