### ISSUE TITLE
[1.1-develop] implement folders filter UI component

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#797]
Implement folders filter UI component.

The component should extend select filter UI component (most likely custom .js and .html) and probably introduce some css as well to render and handle the select in the form of folders.

On the backend side an options provider should be introduced to convert folder structure of `pub/media` directory to options for the folder select.

![image](https://user-images.githubusercontent.com/2028541/69784916-41de5a80-11b7-11ea-9883-e11a84d63a0c.png)

**Comment by nige-one** [comment]
@sivaschenko Do you think it makes sense to introduce a new source interface, since the select UI component relies on https://github.com/magento/magento2/blob/f6405d571110d736fefb7f27925c8748da83c7fa/lib/internal/Magento/Framework/Data/OptionSourceInterface.php#L20
As the select-ui component resolves the optionArray into an internal data structure it would make sense to serve an array of directories and resolve that into select-ui's data structure via an new ui component as wrapper... The optionArray is not needed in that case. What do you think?

**Comment by sivaschenko** [comment]
@nige-one I think we could try that. BTW, I'm going to slightly update and merge https://github.com/magento/adobe-stock-integration/pull/813 today as this PR would introduce the basics needed for other tasks as well, can you please update with the latest code (if any) and move the further development to a separate branch.
