### ISSUE TITLE
Alert appears twice when the folder creation is not successful

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/adobe-stock-integration#840]
### Preconditions (*)

1. M 2.3.3
2. Adobe Stock is configured

### Steps to reproduce (*)

1. On CMS edit page open media gallery
2. Load 5 images from Adobe Stock. One by one without page reload.
Every next save of the image will drastically decrease performance. (Memory leak suspected)
3. Click "Create Folder"
4. Type in "папка"
5. Click "OK"
6. When alert with a message "Please rename the folder Please rename the folder using only letters, numbers, underscores and dashes." appears, click "OK"
7. Click anywhere on the dark overlay

### Expected result (*)

1. Alert appears only once

### Actual result (*)

1. The same alert second time

**Comment by TomashKhamlai** [comment]
So now I am sure that the issue is not connected with Media Gallery only.

**Comment by AnnaShepa** [comment]
@TomashKhamlai  please update description in this case

**Comment by TomashKhamlai** [comment]
@AnnaShepa, thank you for your collaboration)! Did you mean the second step from the precondition or I have missed something else?

**Comment by sivaschenko** [comment]
@TomashKhamlai thanks for the issue! Can you confirm that the issue can be reproduced only with Adobe Stock Integration installed?

**Comment by TomashKhamlai** [comment]
@sivaschenko, I can confirm that the issue is not reproducible on Vanilla Magento. It could be so that the problem is on the Magento side, but it is discoverable only with some extension, for example, Adobe Stock Integration.

**Comment by TomashKhamlai** [comment]
Description was updated

**Comment by drpayyne** [comment]
Hi @TomashKhamlai, I'm not able to reproduce this for some reason. When I click 'OK' on the error modal, I don't get any dark overlay. The error modal just closes. Am I missing anything? Thanks.

**Comment by sivaschenko** [comment]
@chalov-anton can you please retest this issue on the latest code base

**Comment by engcom-Bravo** [comment]
@sivaschenko 
The issue is reproducible on the latest codebase, Magento 2.4-develop & ASI 1.1-develop
The point is to have at least 5 images in the Media Gallery and left mouse click on the page after confirming the first "_Attention: Please rename the folder..._" message
![dark_overlay](https://user-images.githubusercontent.com/51680745/77328716-989f0f80-6d25-11ea-9756-056c3457fb40.gif)

**Comment by sivaschenko** [comment]
Thanks @engcom-Bravo 

@drpayyne can you please check if you can reproduce the issue following the video in the comment above

**Comment by drpayyne** [comment]
Hi @engcom-Bravo, what browser are you using? I tried on Chromium and Firefox and I'm not able to reproduce it for some reason. Here's the video of what happens. 
![adobe-stock-integration-2020-03](https://user-images.githubusercontent.com/22623301/77426409-6ca18e00-6dfa-11ea-80e7-5513189a0973.gif)

I notice that when the first error message is shown for invalid name, the dark overlay is already present, whereas in your video, I see that the first error message has no dark overlay, but on clicking okay, the second error message is shown with a dark overlay.

**Comment by engcom-Bravo** [comment]
Hello @drpayyne 

This is not dependent on the browser version. You are probably not able to reproduce this because you have a faster machine :blush: And after clicking OK on the "_Attention: Please rename the folder..._" message, the "dark overlay" disappears faster than on my machine, and you have no time to click on it
I can only suggest you to try to load more images into the Media Gallery, which might slow down the work.

**Comment by Nazar65** [comment]
PR created at m2 repo https://github.com/magento/magento2/pull/28739
