### ISSUE TITLE
500 (Internal server error) appears in Developer Console if try to apply not valid data in date field (Media Gallery, Uploaded Date or Modification Date filters)

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#881]
### Preconditions (*)
1. The issue will be valid after merging https://github.com/magento/adobe-stock-integration/pull/843
2. Install Magento with Adobe Stock Integration
3. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. Go to **Media Gallery Development**, click **Filters**
2. Type, for example, _1234_ into any **From** or **To** field. Click **Apply Filters** 
3. Open Developer Console in your web browser (F12) and observe 
### Expected result (*)
1. No error appears

### Actual result (*)
1. _Attention. Something went wrong_ message appears 
2. _500 (Internal server error)_ appears in Developer Console
![500 error_1234](https://user-images.githubusercontent.com/45624059/71470689-b0720080-27d5-11ea-88a6-205d99520abe.png)

**Comment by konarshankar07** [comment]
Hello @sivaschenko ,
I started looking into this issue and I'm getting the following error in the error log `PHP Fatal error:  Uncaught Error: Call to a member function format() on null in /var/www/html/magento/app/code/Magento/Ui/Component/Filters/Type/DateRange.php:58\nStack trace:\n#0 /var/www/html/magento/app/code/Magento/Ui/Component/Filters/Type/Range.php(39): Magento\\Ui\\Component\\Filters\\Type\\DateRange->applyFilterByType('gteq', NULL)\n#1 /var/www/html/magento/app/code/Magento/Ui/Component/Filters/Type/Range.php(23): Magento\\Ui\\Component\\Filters\\Type\\Range->applyFilter()\n#2 /var/www/html/magento/app/code/Magento/Ui/Component/Filters/Type/DateRange.php(41): Magento\\Ui\\Component\\Filters\\Type\\Range->prepare()\n#3 /var/www/html/magento/app/code/Magento/Ui/Controller/Adminhtml/Index/Render.php(147): Magento\\Ui\\Component\\Filters\\Type\\DateRange->prepare()\n#4 /var/www/html/magento/app/code/Magento/Ui/Controller/Adminhtml/Index/Render.php(144): Magento\\Ui\\Controller\\Adminhtml\\Index\\Render->prepareComponent(Object(Magento\\Ui\\Component\\Filters\\Type\\DateRange))\n#5 /var/www/html/magento/app/code/Magento/Ui/Controller/Adminhtml/Index/Render.php in /var/www/html/magento/app/code/Magento/Ui/Component/Filters/Type/DateRange.php on line 58, referer: http://local.magento.com/admin/media_gallery/index/index/key/bfcd259e71fff1e59bf0a177a6b9ad1061cceabae787a3077b9b19a8982a76de/`

I think this issue is regarding date validation issue before filter. Correct me If I'm wrong?
Do we need to fix this bug in Magento core or just need to create our filter class to fix the validation issue?
Thanks

**Comment by sivaschenko** [comment]
@konarshankar07 I think we should fix this issue in magento2 core. Ideally, both backend processing and frontend validation should be fixed
